#!/usr/bin/env python3
"""Generates the final TCL script that assembles this project's harvested
capacitance (.caps) + resistance (.TYP) data into ONE combined OpenRCX
rules file spanning gt2n's full real routing-layer space.

Frontside and backside are independent FasterCap solve domains (per
openrcx/README.md), and remain two separate .caps/.TYP data files, but
they get read into a SINGLE init_rcx_model/write_rcx_model with
met_cnt=21 -- not two separate models as originally generated. This is
required, not just tidier: gt2n's real unified tech LEF numbers routing
levels backside-first (1-6, reversed) then frontside (7-21), and
extMain::getResCapTable() unconditionally iterates every routing layer
in the design's loaded tech when extract_parasitics runs, indexing
per-layer tables by that real routing level. A model that only covers
one stack's layer range crashes (index out of bounds) the moment a
design uses layers outside that range -- confirmed via a real segfault
in rcx::extMain::calcRes0 when a frontside-only, locally-1-based model
was loaded against gt2n's real LEF. build_combined_caps.py and
gen_resistance_table.py both already remap their local per-stack 1-based
"Metal N"/"Over N"/"Under N" fields to this real numbering
(frontside: real = local + 6, backside: real = 7 - local) before this
script ever runs, so the .caps/.TYP files it reads here are already in
real-layer-index space.

Mirrors calibration/fasterCap/Makefile's `model:` target in openroad-fork.
wire_index/family mapping is exactly the convention documented in
extRCmodel_solver.cpp's readRCvalues/getAllowedPatternWireNums comment
("for Resistance, wire is 0; for OpenEnded patterns... wire is 1; for
one side OpenEnded patterns... wire is 1; for fully coupled patterns
Over3/Under3, wire is 2; Over5/Under5, wire is 3") and this project's
own wc convention (wc1/wc2 -> wire_index 1, wc3 -> wire_index 2,
wc5 -> wire_index 3). Only 4 pattern families exist in our data (no
OverDiag) -- confirmed by grepping the combined .caps files directly.

Note: passing -wire_index 1 also incidentally pulls in wc3/wc5
patterns' own wire_1 line as extra one-side-open data (per
getAllowedPatternWireNums's `m._over1` logic) -- this is intentional,
documented tool behavior, not a bug in this script.
"""

FAMILIES = ["over", "under", "over_under", "diag"]
STACKS = ["backside", "frontside"]
MET_CNT = 21

TEMPLATE = """# Auto-generated by gen_rules_tcl.py -- assembles a single combined
# OpenRCX rules file spanning gt2n's full real routing-layer space
# (met_cnt=21: backside levels 1-6, frontside levels 7-21) from this
# project's harvested FasterCap capacitance data (gt2n_backside.caps,
# gt2n_frontside.caps) and the analytically-derived resistance tables
# (resistance_backside.TYP, resistance_frontside.TYP).
init_rcx_model -corner_names "TYP" -met_cnt {met_cnt}
{read_lines}
write_rcx_model -file gt2n_combined.rcx.model
"""


def main():
    read_lines = []
    for stack in STACKS:
        for wire_index in (1, 2, 3):
            for family in FAMILIES:
                read_lines.append(
                    f"read_rcx_tables -corner_name TYP -file gt2n_{stack}.caps "
                    f"-wire_index {wire_index} -{family}"
                )
    for stack in STACKS:
        read_lines.append(
            f"read_rcx_tables -corner_name TYP -file resistance_{stack}.TYP"
        )

    content = TEMPLATE.format(
        met_cnt=MET_CNT,
        read_lines="\n".join(read_lines),
    )
    out_path = "gen_rules_combined.tcl"
    with open(out_path, "w") as f:
        f.write(content)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
