# Auto-generated by gen_rules_tcl.py -- assembles a single combined
# OpenRCX rules file spanning gt2n's full real routing-layer space
# (met_cnt=21: backside levels 1-6, frontside levels 7-21) from this
# project's harvested FasterCap capacitance data (gt2n_backside.caps,
# gt2n_frontside.caps) and the analytically-derived resistance tables
# (resistance_backside.TYP, resistance_frontside.TYP).
init_rcx_model -corner_names "TYP" -met_cnt 21
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 1 -over
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 1 -under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 1 -over_under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 1 -diag
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 2 -over
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 2 -under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 2 -over_under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 2 -diag
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 3 -over
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 3 -under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 3 -over_under
read_rcx_tables -corner_name TYP -file gt2n_backside.caps -wire_index 3 -diag
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 1 -over
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 1 -under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 1 -over_under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 1 -diag
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 2 -over
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 2 -under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 2 -over_under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 2 -diag
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 3 -over
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 3 -under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 3 -over_under
read_rcx_tables -corner_name TYP -file gt2n_frontside.caps -wire_index 3 -diag
read_rcx_tables -corner_name TYP -file resistance_backside.TYP
read_rcx_tables -corner_name TYP -file resistance_frontside.TYP
write_rcx_model -file gt2n_combined.rcx.model
